name: Build and Deploy Dashboard React to OpenShift

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Install OpenShift CLI
      run: |
        curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz -o oc.tar.gz
        tar -xzf oc.tar.gz
        sudo mv oc /usr/local/bin/

    - name: Login to OpenShift
      run: |
        oc login --token=sha256~hNNyjFjRnZQgPt4oDsnNAV6mKH434F20aC9PFsVMhAI --server=https://api.rm3.7wse.p1.openshiftapps.com:6443 --insecure-skip-tls-verify

    - name: Set OpenShift Project
      run: |
        oc project t4nm4y-dev

    - name: Install Node.js Dependencies
      run: |
        npm install --legacy-peer-deps
        
    - name: Create New OpenShift Build (if needed)
      run: |
        if ! oc get bc dashboard-react; then
          oc new-build --name=dashboard-react --strategy=docker --binary
        fi

    - name: Start OpenShift Build
      run: |
        oc start-build dashboard-react --from-dir=. --follow

    - name: Deploy React Application
      run: |
        if ! oc get deployment dashboard-react; then
          oc new-app dashboard-react
        else
          oc set image deployment/dashboard-react dashboard-react=image-registry.openshift-image-registry.svc:5000/t4nm4y-dev/dashboard-react:latest
          oc rollout restart deployment/dashboard-react
        fi

    - name: Expose OpenShift Service
      run: |
        if ! oc get svc dashboard-react; then
          oc expose deployment dashboard-react --port=8080 --name=dashboard-react
        fi

    - name: Create OpenShift Route
      run: |
        if ! oc get route dashboard-react; then
          oc expose svc/dashboard-react
        fi

    - name: Secure Route with HTTPS
      run: |
        oc patch route dashboard-react -p '{"spec":{"tls":{"termination":"edge"}}}' || echo "TLS already configured"

    - name: Display Deployed Route
      run: |
        echo "Dashboard React is accessible at: https://$(oc get route dashboard-react -o jsonpath='{.spec.host}')"
